-- MySQL Script generated by MySQL Workbench
-- Tue Feb 25 19:41:59 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema delivery
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `delivery` ;

-- -----------------------------------------------------
-- Schema delivery
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `delivery` ;
USE `delivery` ;

-- -----------------------------------------------------
-- Table `delivery`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delivery`.`table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `delivery`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delivery`.`clientes` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(25) NULL,
  `apellido` VARCHAR(25) NULL,
  `direccion` VARCHAR(45) NULL,
  `cp` VARCHAR(5) NULL,
  `localidad` VARCHAR(15) NULL,
  `provincia` VARCHAR(15) NULL,
  `telefono` VARCHAR(12) NULL,
  PRIMARY KEY (`id_cliente`),
  UNIQUE INDEX `id_cliente_UNIQUE` (`id_cliente` ASC) INVISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `delivery`.`tienda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delivery`.`tienda` (
  `id_tienda` INT NOT NULL AUTO_INCREMENT,
  `direccion` VARCHAR(45) NULL,
  `cp` VARCHAR(8) NULL,
  `localidad` VARCHAR(15) NULL,
  `provincia` VARCHAR(15) NULL,
  PRIMARY KEY (`id_tienda`),
  UNIQUE INDEX `id_tienda_UNIQUE` (`id_tienda` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `delivery`.`empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delivery`.`empleado` (
  `id_empleado` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(20) NULL,
  `apellidos` VARCHAR(20) NULL,
  `nif` VARCHAR(10) NULL,
  `telefono` VARCHAR(12) NULL,
  `categoria` ENUM('repartidor', 'cocinero') NULL,
  `tienda_id_tienda` INT NOT NULL,
  PRIMARY KEY (`id_empleado`, `tienda_id_tienda`),
  UNIQUE INDEX `id_empleado_UNIQUE` (`id_empleado` ASC) VISIBLE,
  INDEX `fk_empleado_tienda1_idx` (`tienda_id_tienda` ASC) VISIBLE,
  CONSTRAINT `fk_empleado_tienda1`
    FOREIGN KEY (`tienda_id_tienda`)
    REFERENCES `delivery`.`tienda` (`id_tienda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `delivery`.`pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delivery`.`pedidos` (
  `id_pedido` INT NOT NULL,
  `clientes_id_cliente` INT NOT NULL,
  `tienda_id_tienda` INT NOT NULL,
  `fecha/hora` DATETIME NULL,
  `tipoPedido` ENUM('domicilio', 'recoger') NULL,
  `precioTotal` DECIMAL(5,2) NULL,
  `empleado_id_empleado` INT NULL,
  `fecha/hora_entrega` DATETIME NULL,
  PRIMARY KEY (`id_pedido`, `clientes_id_cliente`, `tienda_id_tienda`, `empleado_id_empleado`),
  INDEX `fk_pedidos_clientes1_idx` (`clientes_id_cliente` ASC) VISIBLE,
  INDEX `fk_pedidos_tienda1_idx` (`tienda_id_tienda` ASC) VISIBLE,
  INDEX `fk_pedidos_empleado1_idx` (`empleado_id_empleado` ASC) VISIBLE,
  CONSTRAINT `fk_pedidos_clientes1`
    FOREIGN KEY (`clientes_id_cliente`)
    REFERENCES `delivery`.`clientes` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedidos_tienda1`
    FOREIGN KEY (`tienda_id_tienda`)
    REFERENCES `delivery`.`tienda` (`id_tienda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedidos_empleado1`
    FOREIGN KEY (`empleado_id_empleado`)
    REFERENCES `delivery`.`empleado` (`id_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `delivery`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delivery`.`categoria` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT,
  `categoria` VARCHAR(15) NULL,
  PRIMARY KEY (`id_categoria`),
  UNIQUE INDEX `id_categoria_UNIQUE` (`id_categoria` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `delivery`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delivery`.`producto` (
  `id_producto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(25) NULL,
  `tipo` ENUM('pizza', 'hamburguesa', 'bebida') NULL,
  `descripcion` MEDIUMTEXT NULL,
  `imagen` VARCHAR(45) NULL,
  `precio` DECIMAL(5,2) NULL,
  `categoria_id_categoria` INT NOT NULL,
  PRIMARY KEY (`id_producto`, `categoria_id_categoria`),
  UNIQUE INDEX `id_producto_UNIQUE` (`id_producto` ASC) VISIBLE,
  INDEX `fk_producto_categoria_idx` (`categoria_id_categoria` ASC) VISIBLE,
  CONSTRAINT `fk_producto_categoria`
    FOREIGN KEY (`categoria_id_categoria`)
    REFERENCES `delivery`.`categoria` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `delivery`.`pedidos_has_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delivery`.`pedidos_has_producto` (
  `id_ped_pro` INT NOT NULL,
  `pedidos_id_pedido` INT NOT NULL,
  `producto_id_producto` INT NOT NULL,
  `cantidad` INT NULL,
  PRIMARY KEY (`id_ped_pro`, `pedidos_id_pedido`, `producto_id_producto`),
  INDEX `fk_pedidos_has_producto_producto1_idx` (`producto_id_producto` ASC) VISIBLE,
  INDEX `fk_pedidos_has_producto_pedidos1_idx` (`pedidos_id_pedido` ASC) VISIBLE,
  UNIQUE INDEX `id_ped_pro_UNIQUE` (`id_ped_pro` ASC) VISIBLE,
  CONSTRAINT `fk_pedidos_has_producto_pedidos1`
    FOREIGN KEY (`pedidos_id_pedido`)
    REFERENCES `delivery`.`pedidos` (`id_pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedidos_has_producto_producto1`
    FOREIGN KEY (`producto_id_producto`)
    REFERENCES `delivery`.`producto` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
